Repository t2linux/wiki, pull requests merged in 2021-02, with the labels that each got.

#1 Manjaro Wiki Files
  .markdownlint.json
  docs/distributions/manjaro/building.md
  docs/distributions/manjaro/faq.md
  docs/distributions/manjaro/home.md
  docs/distributions/manjaro/installation.md
  docs/distributions/manjaro/wifi-installation.md
  mkdocs.yml
Labels: documentation, good first issue

#2 Manjaro: Remove generic part from the wifi install and reference guides/wifi
  docs/distributions/manjaro/wifi-installation.md
Labels: documentation

#3 Ubuntu wiki files
  docs/distributions/ubuntu/faq.md
  docs/distributions/ubuntu/home.md
  docs/distributions/ubuntu/installation.md
  mkdocs.yml
Labels: documentation, good first issue

#7 Separate Audio page, Links to new guides in FAQs, added to triple boot page
  docs/distributions/manjaro/faq.md
  docs/distributions/ubuntu/faq.md
  docs/guides/audio-config.md
  docs/guides/dkms.md
  docs/guides/windows.md
  mkdocs.yml
Labels: documentation, navigation

#15 Added the Ubuntu Building page to mkdocs
  mkdocs.yml
Labels: navigation
